---
roles:
  - name: buluma.bootstrap
  - name: buluma.epel
  - name: buluma.python_pip
  - name: buluma.mysql
  - name: buluma.nginx
  - name: buluma.php
collections:
  - name: community.general
  - name: community.mysql
