---
- name: Main | Load distribution variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"
- name: Main | Install distribution PHP packages
  ansible.builtin.package:
    name: "{{ lemp_php_packages }}"
    state: present
  when: php_version == 'distro'
  notify: Restart php-fpm
# Separator for the pre-commit handler parser.
- name: Main | Include lemp-php56 tasks
  ansible.builtin.import_tasks: lemp-php56.yml
- name: Main | Include lemp-php70 tasks
  ansible.builtin.import_tasks: lemp-php70.yml
- name: Main | Include composer tasks
  ansible.builtin.import_tasks: composer.yml
- name: Main | Include nginx tasks
  ansible.builtin.import_tasks: nginx.yml
- name: Main | Include sendmail tasks
  ansible.builtin.import_tasks: sendmail.yml
- name: Main | Include root-config tasks
  ansible.builtin.import_tasks: root-config.yml
