---
- name: Main | Include lemp-php56 tasks
  ansible.builtin.import_tasks: lemp-php56.yml
- name: Main | Include lemp-php70 tasks
  ansible.builtin.import_tasks: lemp-php70.yml
- name: Main | Include composer tasks
  ansible.builtin.import_tasks: composer.yml
- name: Main | Include nginx tasks
  ansible.builtin.import_tasks: nginx.yml
- name: Main | Include sendmail tasks
  ansible.builtin.import_tasks: sendmail.yml
- name: Main | Include root-config tasks
  ansible.builtin.import_tasks: root-config.yml
- name: Install all updates
  ansible.builtin.dnf: # noqa: package-latest
    name: "*"
    state: latest
