---
- name: Install nginx
  notify:
  - restart nginx
  yum:
    name: nginx16
    state: present
- file:
    group: nginx
    mode: 700
    owner: nginx
    path: /var/lib/nginx/cache
    state: directory
  name: Make /var/lib/nginx/cache directory
  notify:
  - restart nginx
- file:
    group: nginx
    mode: 700
    owner: nginx
    path: /etc/nginx/ssl
    state: directory
  name: Make /etc/nginx/ssl directory
  notify:
  - restart nginx
