---
- name: nginx | Install nginx
  notify:
    - Restart nginx
  ansible.builtin.dnf:
    name: nginx16
    state: present
- name: nginx | Make /var/lib/nginx/cache directory
  ansible.builtin.file:
    group: nginx
    mode: "0700"
    owner: nginx
    path: /var/lib/nginx/cache
    state: directory
  notify:
    - Restart nginx
- name: nginx | Make /etc/nginx/ssl directory
  ansible.builtin.file:
    group: nginx
    mode: "0700"
    owner: nginx
    path: /etc/nginx/ssl
    state: directory
  notify:
    - Restart nginx
