---
- name: root-config | Deploy /etc/nginx/nginx.conf
  ansible.builtin.copy:
    dest: /etc/nginx/nginx.conf
    mode: "0644"
    src: etc+nginx+nginx.conf
- name: root-config | Deploy /etc/nginx/conf.d/default.conf
  ansible.builtin.copy:
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
    src: etc+nginx+conf.d+default.conf
- name: root-config | Deploy /etc/php-fpm.d/www.conf
  ansible.builtin.copy:
    dest: /etc/php-fpm.d/www.conf
    mode: "0644"
    src: etc+php-fpm.d+www.conf
