---
- name: Install Sendmail
  with_items:
    - sendmail
    - sendmail-cf
    - make
    - mailx
  yum:
    name: "{{ item }}"
    state: present
- name: Remove Postfix
  yum:
    name: postfix
    state: absent
- copy:
    dest: /etc/mail/aliases
    src: /etc/aliases
  name: Copy Sendmail config
- name: Enable Sendmail service
  service:
    enabled: true
    name: sendmail
