---
- name: sendmail | Install Sendmail
  with_items:
    - sendmail
    - sendmail-cf
    - make
    - mailx
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
- name: sendmail | Remove Postfix
  ansible.builtin.dnf:
    name: postfix
    state: absent
- name: sendmail | Copy Sendmail config
  ansible.builtin.copy:
    dest: /etc/mail/aliases
    mode: preserve
    remote_src: true
    src: /etc/aliases
- name: sendmail | Enable Sendmail service
  ansible.builtin.service:
    enabled: true
    name: sendmail
