---
name: CI
true:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  vim:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Test Vim
      run: ansible-playbook -K tests/test.yml -vvv
